version: "3.7"

services:
  itr-app:
    container_name: itr-app
    build:
      context: .
    environment:
      - DB_URL=${DB_URL}
      - DB_DRIVER_CLASS_NAME=${DB_DRIVER_CLASS_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - LIQUIBASE_CHANGE_LOG=${LIQUIBASE_CHANGE_LOG}
      - JWT_KEYWORD=${JWT_KEY}
      - JWT_PREFIX=${JWT_PREFIX}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JWT_HEADER=${JWT_HEADER}
      - RABBIT_PASS=${RABBIT_PASS}
      - RABBIT_USERNAME=${RABBIT_USERNAME}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_ROUTING=${RABBIT_ROUTING}
      - RABBIT_QUEUE=${RABBIT_QUEUE}
      - RABBIT_EXCHANGE=${RABBIT_EXCHANGE}
    ports:
      - 8080:8080
    depends_on:
      - db
      - rabbit
      - rabbit-consumer
  db:
    container_name: itr-app-postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${PASS}
      - POSTGRES_USER=${USER}
    volumes:
      - dbstore:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbit:
    container_name: itr-app-rabbitmq
    image: rabbitmq:3-management-alpine
    volumes:
             - rabbitmq_log:/var/log/rabbitmq
             - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  rabbit-consumer:
    container_name: rabbit-consumer
    build:  /home/alexandr/IdeaProjects/RabbitConsumer/.
    environment:
      - RABBIT_PASS=${RABBIT_PASS}
      - RABBIT_USERNAME=${RABBIT_USERNAME}
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_HOST=${RABBIT_HOST}
      - RABBIT_ROUTING=${RABBIT_ROUTING}
      - RABBIT_QUEUE=${RABBIT_QUEUE}
      - RABBIT_EXCHANGE=${RABBIT_EXCHANGE}

volumes:
  dbstore:
  rabbitmq_log:
  rabbitmq_data:
